GET http://localhost:8000/v1/item/get 

###

POST http://localhost:8000/v1/item/create/test thoi ma


###

PUT http://localhost:8000/v1/item/edit
Content-Type: application/json

{
    "title" : "test",
    "status" : "DONE"
}