GET http://localhost:8000/v1/item/get 

###

POST http://localhost:8000/v1/item/create/test test item 2


###
PUT http://localhost:8000/v1/item/edit
Content-Type: application/json

{
    "title" : "test test item 1",
    "status" : "PENDING"
}

###
DELETE http://localhost:8000/v1/item/delete
Content-Type: application/json

{
    "title" : "test test item 1",
    "status" : "DONE"
}

###

GET http://localhost:8000/v1/auth/login